version: '3'

volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: tim2206/foodgram_backend
    env_file: .env
    volumes:
      - static_volume:/app/collected_static
      - media_volume:/app/media
    depends_on:
      - db
  frontend:
    image: tim2206/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  infra:
    image: tim2206/foodgram_gateway
    env_file: .env
    ports:
      - 9080:80
    volumes:
      - static_volume:/static
      - media_volume:/media
    depends_on:
      - backend
