"""Константы проекта."""

EMAIL_MAX_LENGTH = 254
INGREDIENT_MEASUREMENT_UNIT_MAX_LENGTH = 64
INGREDIENT_NAME_MAX_LENGTH = 128
MAX_REPR_LENGTH = 25
MIN_COOKING_TIME = 1
INVALID_COOKING_TIME_MESSAGE = (
    f'Значение должно быть больше {MIN_COOKING_TIME}.'
)
PAGE_SIZE = 6
PASSWORD_MAX_LENGTH = 30
RECIPE_NAME_MAX_LENGTH = 128
TAG_MAX_LENGTH = 32
USERNAME_MAX_LENGTH = 150
USERNAME_REGEX = r'^[\w.@+-]+\Z'
