"""Константы проекта."""

AVATAR_PATH = 'me/avatar'
EMAIL_MAX_LENGTH = 254
FAVORITE_PATH = 'favorite'
INGREDIENT_MEASUREMENT_UNIT_MAX_LENGTH = 64
INGREDIENT_NAME_MAX_LENGTH = 128
MAX_REPR_LENGTH = 25
MIN_COOKING_TIME = 1
INVALID_COOKING_TIME_MESSAGE = (
    f'Значение должно быть больше {MIN_COOKING_TIME}.'
)
PAGE_SIZE = 6
PASSWORD_CHANGE_PATH = 'set_password'
RECIPE_LINK_PATH = 'get-link'
RECIPE_NAME_MAX_LENGTH = 128
SHOPPING_CART_PATH = 'shopping_cart'
SUBSCRIBE_PATH = 'subscribe'
SUBSCRIPTIONS_PATH = 'subscriptions'
TAG_MAX_LENGTH = 32
USERNAME_MAX_LENGTH = 150
USERNAME_REGEX = r'^[\w.@+-]+\Z'
USER_PROFILE = 'me'
