# Generated by Django 3.2.3 on 2024-11-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_shortlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlink',
            name='short_url',
            field=models.URLField(unique=True),
        ),
    ]
