# Generated by Django 3.2.3 on 2024-11-14 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_shortlink_short_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortlink',
            old_name='full_url',
            new_name='full_link',
        ),
        migrations.RenameField(
            model_name='shortlink',
            old_name='short_url',
            new_name='short_link',
        ),
    ]
