# Generated by Django 3.2.3 on 2024-11-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20241114_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlink',
            name='short_link',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
    ]
