# Generated by Django 3.2.3 on 2024-11-07 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20241105_1726'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipeingredients',
            name='unique_ingredient_for_recipe',
        ),
    ]
