# Generated by Django 3.2.3 on 2024-11-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_remove_recipeingredients_unique_ingredient_for_recipe'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='recipeingredients',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredients'), name='unique_ingredient_for_recipe'),
        ),
    ]
