# Generated by Django 3.2.3 on 2024-11-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_foodgramuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodgramuser',
            name='password',
            field=models.TextField(verbose_name='Пароль'),
        ),
    ]
