# Generated by Django 3.2.3 on 2024-11-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_foodgramuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodgramuser',
            name='password',
            field=models.CharField(max_length=30, verbose_name='Пароль'),
        ),
    ]
