# Generated by Django 3.2.3 on 2024-11-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_foodgramuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodgramuser',
            name='password',
            field=models.TextField(verbose_name='Пароль'),
        ),
    ]
