# Generated by Django 3.2.3 on 2024-11-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_foodgramuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodgramuser',
            name='avatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='users/avatars/', verbose_name='Аватар пользователя'),
        ),
    ]
